server:
  port: ${PORT:8090}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: MovieCatalogService
          uri: lb://movie-catalog-service
#         uri: http://localhost:8080
          predicates:
            - Path=/catalog/**
          filters:
            - CustomFilter
